sources:
  clients: http://www.mocky.io/v2/5808862710000087232b75ac
  policies: http://www.mocky.io/v2/580891a4100000e8242b75c5

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://127.0.0.1:33060/privalia
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver